  14-sorting-strings-in-alphabetical-order[m
  15-finding-the-prime-numbers[m
* [32m55-prime_num_generator[m
  main[m
  [31mremotes/origin/11-upload-base-readme-file[m
  [31mremotes/origin/14-sorting-strings-in-alphabetical-order[m
  [31mremotes/origin/15-finding-the-prime-numbers[m
  [31mremotes/origin/32-checking-prime-numbers[m
  [31mremotes/origin/34-missing-number[m
  [31mremotes/origin/55-prime_num_generator[m
  [31mremotes/origin/6-longest-substring[m
  [31mremotes/origin/7-anagram-checker[m
  [31mremotes/origin/8-is-number-odd[m
  [31mremotes/origin/9-factorial[m
  [31mremotes/origin/GP25_Group-Norms[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/Max-Integer[m
  [31mremotes/origin/Min-Integer[m
  [31mremotes/origin/binary-search[m
  [31mremotes/origin/communication[m
  [31mremotes/origin/constraints[m
  [31mremotes/origin/count-capitalized-words[m
  [31mremotes/origin/is-leap-year[m
  [31mremotes/origin/is-palindrome[m
  [31mremotes/origin/ka-branch[m
  [31mremotes/origin/learning-goals[m
  [31mremotes/origin/main[m
  [31mremotes/origin/missing-numbers[m
  [31mremotes/origin/multiplication-table[m
  [31mremotes/origin/revert-44-missing-numbers[m
